pipeline {

    agent any



    stages {

        stage('Build') {

            steps {

                git 'https://github.com/MayankSaxena23/AI-Image-Generator.git'

            }   

        }

    }

}
